version: '2'

services:
  insta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insta
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules